#!/usr/bin/env python
"""
Chunking strategy evaluation script.
Compares retrieval quality across different chunk sizes.
"""
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from rag_utils import (
    extract_text_from_pdf,
    chunk_text,
    build_faiss_index,
    embed_query,
    load_embedding_model,
)
import faiss


PDF_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "pdf_for_upload_test.pdf")
CHUNK_SIZES = [300, 500, 800]
OVERLAP_SENTENCES = 2
TEST_QUESTIONS = [
    "What is the main contribution of the Attention Is All You Need paper?",
    "How does multi-head attention work?",
    "What are the key innovations of the Transformer architecture?",
]
TOP_K = 3
PREVIEW_CHARS = 150
OUTPUT_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "chunking_report.md")


def run_evaluation():
    print(f"Loading PDF: {PDF_PATH}")
    pages_text = extract_text_from_pdf(PDF_PATH)
    print(f"Extracted {len(pages_text)} pages")

    embed_model = load_embedding_model()
    print(f"Loaded embedding model: {embed_model}")

    report_lines = []
    report_lines.append("# Chunking Strategy Comparison Report\n")
    report_lines.append(f"**PDF**: {os.path.basename(PDF_PATH)}  ")
    report_lines.append(f"**Embedding Model**: BAAI/bge-small-en-v1.5  ")
    report_lines.append(f"**Overlap Sentences**: {OVERLAP_SENTENCES}  ")
    report_lines.append(f"**Test Questions**: {len(TEST_QUESTIONS)}  ")
    report_lines.append(f"**Top-K Retrieved**: {TOP_K}  \n")

    for chunk_size in CHUNK_SIZES:
        print(f"\n{'='*60}")
        print(f"Testing chunk_size={chunk_size}")
        print(f"{'='*60}")

        chunks, chunk_pages = chunk_text(pages_text, chunk_size=chunk_size, overlap_sentences=OVERLAP_SENTENCES)
        print(f"Produced {len(chunks)} chunks")

        index, _ = build_faiss_index(chunks, embed_model)

        report_lines.append(f"## Chunk Size: {chunk_size}\n")
        report_lines.append(f"**Number of chunks**: {len(chunks)}  \n")

        for q_idx, question in enumerate(TEST_QUESTIONS):
            print(f"\n  Question {q_idx+1}: {question}")
            q_emb = embed_query(embed_model, question)
            D, I = index.search(q_emb, k=min(TOP_K, len(chunks)))

            report_lines.append(f"### Question {q_idx+1}: {question}\n")
            report_lines.append("| Rank | Page | Similarity | Chunk Preview |\n")
            report_lines.append("|------|------|------------|---------------|\n")

            for rank, (idx, score) in enumerate(zip(I[0], D[0])):
                if idx == -1:
                    continue
                snippet = chunks[idx][:PREVIEW_CHARS].replace("\n", " ")
                if len(chunks[idx]) > PREVIEW_CHARS:
                    snippet += "..."
                snippet = snippet.replace("|", "\\|")
                page_num = chunk_pages[idx]
                report_lines.append(f"| {rank+1} | {page_num} | {score:.4f} | {snippet} |\n")
                print(f"    Rank {rank+1}: page {page_num}, score {score:.4f}, preview: {snippet[:80]}...")

            report_lines.append("\n")

    report_lines.append("---\n")
    report_lines.append("*Generated by scripts/evaluate_chunking.py*\n")

    report_content = "".join(report_lines)
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write(report_content)

    print(f"\nReport written to: {OUTPUT_PATH}")


if __name__ == "__main__":
    run_evaluation()